return PlaceObj('ModDef', {
	'title', "Blood Moon & New Eden Crash Landing",
	'description', 'A family of Space Pilgrims on a quest for a new home barely escape their doomed ship "Thunder Downunder" that just rusted out after many generations in space. This is the story of survival of a single family that made it out in a pod alive. EXCEPT FOR THE MISSING 7 SIBLINGS that must have perished when systems and life support failed.\n\n\nFEATURES:\nWinter + Night Start\nBasic Tech Researched\nBlood Moon + A brief time to build, then endless raids (AND BUGMEATS!@)\n\nCAST: (OPTIONAL SO FAR AND WIP :)\nFather C. C. Carmichael: Sole practitioner of an ancient spiritual martial faith. Can build unique weapons, but only after advancing.\nAmelia C. C. Carmichael: Mother of the cult - PREGNANT - WITH TRIPLETS - Will the colony survive to see them born?\nSister Christy: Daughter\nMiguel: Son of the Faith, Lover of Christy\nRoman Cheeseburger: Son of the faith, Lover of Christy',
	'image', "Mod/n6Stmnj/Images/bloodMoon-f.png",
	'last_changes', "Update Desc",
	'id', "n6Stmnj",
	'author', "bexork",
	'version_minor', 2,
	'version', 448,
	'lua_revision', 233360,
	'saved_with_revision', 352677,
	'has_data', true,
	'saved', 1717736324,
	'screenshot1', "Mod/n6Stmnj/Images/StrandedSteam_btYLhQ4cEa.jpg",
	'screenshot2', "Mod/n6Stmnj/Images/StrandedSteam_Fw01Wuw6Q8.jpg",
	'screenshot3', "Mod/n6Stmnj/Images/StrandedSteam_yDa9wvpc5s.jpg",
	'screenshot4', "Mod/n6Stmnj/Images/StrandedSteam_3AB55WjZ3S.png",
	'screenshot5', "Mod/n6Stmnj/Images/space-cheese-burger.jpg",
	'steam_id', "3255848382",
	'TagCharacters', true,
	'TagGameplay', true,
	'TagResearch', true,
})